### PR TITLE
Completely remove PrivacyTools.io from guide

### PR DESCRIPTION
**Pull request by pterocles**
### I find this type of behavior disgusting and we need to completely remove PTIO from the entire guide.

PTIO contains many links to sponsored/affiliate content. This is not normally an issue. I understand there is a need to have these things, and that it costs money to run servers and websites and things.

However, it has come to my attention that, when viewing mobile links, the site does NOT display any "affiliate" or "sponsor" notices. 

An example of this:

#### Code:
```
<h5 class="app"><a href="hxxps://www.privacytools.xx/go/nordvpn-vpn" target="_blank" class="app">
NordVPN: 60 USD Yearly - Most Servers Available</a> <i class="fas fa-link fa-sm hideicon"></i></h5>
```

This is just one of many shady things that I've seen on their desktop vs mobile experience. I find this disgusting. I will place screenshots of the differences.

### CODE REVIEW

**Comment by pterocles** [comment]
They're not clearly shown except for Desktop. They go out of their way to hide it on mobile.

**Comment by henryistaken** [comment]
> Disagree, sponsored links are clearly shown

On desktop, which doesn't even represent the majority of site visitors nowadays.

> There is no reason to unlink them than any other commercial, non-foss, proprietary references.

If the goal is to properly educate users on your own site and point them towards transparent external sites, I would hope that this behavior would at least be given as a disclaimer or warning before you recommend the site. I know there is already a much-needed disclaimer beneath the references to TNO/PTIO/PG/Techlore for the presence of affiliates/sponsors/merchandising, but this seems to go above that due to the user not even being able to recognize what's sponsored on the site. (on mobile, which represents the majority of site visits on the internet) Additionally, it seems that PTIO has actively chosen to prioritize sponsors/affiliates while actively excluding quality recommendations (IVPN & Mullvad in particular) - which I would consider a red flag, but obviously that's your decision to make as it's your guide.

> We also do not unlink other projects hostile towards ours.

Very valid decision. I know over at Techlore we've received some hate for delisting a project that was legally threatening us. (and others) Though this situation seems different, as they aren't being hostile - but rather misleading to their own visitors. I think it's worth at least asking at what point will you consider changing/modifying recommendations if your external sources lose credibility? And yes, this would applies to ourselves at Techlore too, I *hope* people would be furious if we did this whilst delisting two of the most recommended VPN services in the privacy community.

**Comment by pterocles** [comment]
> point them towards transparent external sites

The goal is to eventually become a single, effective guide for anonymity and security. I think it does that well.

> there is already a much-needed disclaimer beneath the references to TNO/PTIO/PG/Techlore for the presence of affiliates/sponsors/merchandising, but this seems to go above that due to the user not even being able to recognize what's sponsored on the site.

This is my whole point. That's shady. That's it. Period.

>  as they aren't being hostile - but rather misleading to their own visitors. I think it's worth at least asking at what point will you consider changing/modifying recommendations if your external sources lose credibility?

That's pretty much as hostile toward their users as it can get. They're effectively saying, "We can hide it, and nobody will notice, and if they do we'll just say ____ ." 

No. I am uncompromisingly against the use of these hidden affiliate links.

**Comment by pterocles** [comment]
Locked.

The owner has replaced the affiliated and sponsored tags for mobile viewers where the tags are applicable.

**Pull request closed without merging**
