### PR TITLE
Make Appendix Z more readable and make it obvious it's step-by-step

### LINKED ISSUE #146: Appendix Z where we describe purchasing cryptocurrency anonymously needs formatting fixes
Not using bulleted style format like the rest of the guide. 
Not formatting properly because of indentations.
We don't need a list inside of a list inside of a list with a bold warning in it.

### PR DESCRIPTION
**Pull request by pterocles**
Also fix indentation that is making it a code block in some places.

Fixes #146

### CODE REVIEW

**Comment by dan-kir** [comment]
I can vouch for Sparrow wallet. Their implementation of CoinJoin (Whirlpool) is the same as Samourai wallet.  It is feature rich, FOSS and recommended by many in the crypto privacy space.

**Comment by pterocles** [comment]
> I can vouch for Sparrow wallet. Their implementation of CoinJoin (Whirlpool) is the same as Samourai wallet. It is feature rich, FOSS and recommended by many in the crypto privacy space.

If there's anything to be changed content wise, since this is just the formatting, then it needs another issue for discussion. As far as I'm aware, Samourai is good; but I've never extensively tested Sparrow, however, so maybe that's in order.

**Comment by dan-kir** [comment]
> > I can vouch for Sparrow wallet. Their implementation of CoinJoin (Whirlpool) is the same as Samourai wallet. It is feature rich, FOSS and recommended by many in the crypto privacy space.
> 
> If there's anything to be changed content wise, since this is just the formatting, then it needs another issue for discussion. As far as I'm aware, Samourai is good; but I've never extensively tested Sparrow, however, so maybe that's in order.

Created a new issue https://github.com/Anon-Planet/thgtoa/issues/148

**Review by dan-kir — APPROVED** [review]

**Comment by pterocles** [comment]
It's probably not necessary to have the extra paranoid options, but I'd like to run it by the rest of the team before removing the whole section, which does offer an explanation as to why we don't recommend those wallets. Might even require another PR.

**Comment by pterocles** [comment]
Well, make a PR for it and I'll resolve the conflicts later. I'm not trying to mix content removal and fixes in one PR.

**Pull request merged**
