### PR TITLE
Added link to countering linguistic analysis

### PR DESCRIPTION
**Pull request by TwoSixtyThreeFiftyFour**
Added link to Appendix A4 to countering forensics linguistic analysis 

https://seirdy.one/posts/2022/07/09/stylometric-fingerprinting-redux/

### CODE REVIEW

**Review by pterocles — APPROVED** [review]
This blog is a good resource.

**Comment by Seirdy** [comment]
Thanks for the shout-out. A couple areas where I *slightly* disagree with the current advice:

Most of the advice regarding localized symbols/language can be covered by a sufficiently thorough style guide (like The Economist's). I think there's value in having "one place to look/one resource to learn" as a "source of truth"; it simplifies a lot of things.

It's important to keep the difficulty level for stylometric fingerprinting resistance low; if it's too difficult, the labor involved could make writing seem artificial and also make people more likely to give up altogether. That's part of the reason why I recommend just learning a style guide instead of worrying about all these details.

Absolutely *nothing* beats a talented human editor. Try identifying the individual writers of <cite>The Economist</cite> for the main sections (not the obituaries or the supplementary columns named after various economists; they relax the style guide for those). It's difficult---perhaps impossible---since they all share the same strict editor.

**Comment by NobodySpecial256** [comment]
Regarding the advice to have a human editor, is this really practical? For one, it requires you to actually *know* someone qualified to be your editor, and second, it requires you to be able to trust them.

That advice might make sense for people who simply want to write articles anonymously, but it seems impractical for a guide that is tied less with any specific activity, and more on remaining anonymous more generally.

The use of style guides is interesting advice, but as with the advice of using an editor, I'm not sure how well it translates to anonymity in a broader sense than simply publishing articles.

**Comment by NobodySpecial256** [comment]
It's definitely good advice, I'm just not sure how well it works in a broader context.

**Comment by pterocles** [comment]
It's more useful for groups to have a common style guide such as *The Economist*, which is aimed more toward smaller works like publications for magazines and articles in newspapers. It ensures no textual anomalies, where those anomalies can possibly be narrowing factors in identifying the author. I tend to fallback on that particular style guide for small publications like blog posts. It helps to keep the content clean and avoid identifying aphorisms and using common language. "The paragraph," according to Fowler, "is a unit of thought, not of length." It's best to keep sentences short and concise, and to avoid any useful identifying thoughts. 

But the more important thing, that no human writer or editor can avoid forever, is that anomalies that identify a person through their grammar aren't always caught by tools or review by another (trusted) person. You can, given time and enough willpower, discover authors of text simply by analyzing speech patterns. Someone with any dialect has this identifying speech pattern.

Someone that phrases the day before a common American holiday, in reference to the day before it, can be pointed out as having mid-western roots in one or two particular states. Since that phrase is typical among teens and young adults in that area, it's a sufficient data point to use against someone who wishes to remain anonymous.

Effectively, your words are more identifying that people realize and there are some things you simply can't avoid giving away. It may take months or even years, but it's not outside of the realm of possibility if an adversary has the time to commit.

We referenced your blog post after much thought about this. It's a great starting point, but for larger bodies of work, it's not enough to have a style guide alone. It requires reviewing your own writing behavior and picking out identifying characteristics and other things that can be narrowing factors. You then apply these to your rewriting of the original words. Only then do you alter the sentences in ways that you don't regularly write in your dialect. This, again, is still not enough, because although seemingly paranoid, you can still be identified with the amount you write per paragraph and the incredibly specific nuances of your own thoughts.

Linguistics is more than style, but it's still conquerable given time. You can't trust another person to do this for you.

**Pull request merged**
