### PR TITLE
Fix chart being out of date/build table in Kramdown

### PR DESCRIPTION
**Pull request by pterocles**
# Opening a draft to fix the chart

- [x] rebuild in Kramdown syntax
- [ ] update some of the information with new data
- [x] possibly remove hardlinks via `fnref` and replace with bold `[XX]`

### CODE REVIEW

**Comment by thanharrison** [comment]
> What's up with those `(1:1)` ? That show up in the rendered version of both tables ?

It's because with Kramdown it's not possible to link to anything from inside the chart.

> I don't get the "nuke references one" explain it to me like at a 5 yo plz ? you replaced [x] by [x] ? Which refers to nothing and won't work in kramdown ? it has to be [^x] ?

You can't link from inside a Kramdown chart. It must be done in HTML to link anywhere. So that's why I rebuilt using KD and then I linked the refs using bold citations for the reader to look for. No, it's not automatic. Yes, I don't think HTML is a good way to go for something like this. It's too hard to maintain the way it was before.

**Comment by thanharrison** [comment]
I always test a local copy of the guide both manually & with the autobuild. I also build a copy of the site with Jekyll. That's done automatically with the Makefile, but I have my own Makefile that nukes the signatures because obviously I don't need to sign anything, just test the build.

**Comment by thanharrison** [comment]
> well why don't you create a new repo "tests/proposals" and make a something.github.io with your version/changes so we can see the actual fully built changes ?

Too much conflict with branches, might accidentally commit a copy of the commit with my own domain instead, might mess up master. Too many issues. You can, if you want. I know it works using Jekyll and that's all I need.

**Comment by thanharrison** [comment]
@NobodySpecial256 What do you think? Do you prefer the old buggy format or do you want to change to this one that doesn't have embedded references in the cells? Personally, I think it works better as static bold text in the cells that you can reference further in the legend.

**Comment by pterocles** [comment]
Resolved but reconsidering slightly.

**Comment by pterocles** [comment]
Closing as this is a stale PR and no one else has reviewed.

**Pull request closed without merging**
